RELEVANCE_PROMPT = (
    "Determine if this document is a carbon emissions or environmental compliance document.\n\n"
    "Valid types: Carbon Credit Certificate, Emission Report, Carbon Offset Certificate, "
    "GHG Inventory Report, Sustainability Certificate, ISO 14064 Certificate.\n\n"
    "Set is_relevant=true if the document contains any of: carbon, CO2, emissions, greenhouse gas, "
    "GHG, sustainability, environmental, climate, carbon footprint, carbon offset, carbon credit, "
    "ISO 14064, GHG Protocol, Verra, Gold Standard, PAS 2060, scope 1/2/3, tonnes CO2e, tCO2e, "
    "emission factor, verification, certification.\n\n"
    "Set is_relevant=false ONLY for clearly unrelated documents: plain invoices, employment contracts, "
    "bank statements, medical records, payslips, NDAs, meeting minutes with no environmental content.\n\n"
    "When in doubt set is_relevant=true.\n\n"
    "Confidence 0-100: obvious carbon certificate=90-100, clearly sustainability-related=75-90, "
    "some environmental content=60-75, marginal=40-60, clearly unrelated=0-30.\n\n"
    "indicators: list 1-3 specific things you observed supporting your classification.\n"
    "document_type: pick the closest from the valid types listed above."
)

AUTHENTICITY_PROMPT = (
    "Assess the authenticity of this carbon compliance document.\n\n"
    "Score 50-100 (minimum 50 because digital PDFs are legitimate):\n"
    "- All key fields present (org name, cert number, dates, CO2 value, issuing authority, "
    "verification standard): 88-100\n"
    "- Most fields present, 1-2 minor gaps: 75-88\n"
    "- Several fields present, notable gaps: 62-75\n"
    "- Minimal content, heavily incomplete: 50-62\n\n"
    "indicators: list up to 5 positive elements you observe "
    "(letterhead, cert number, dates, CO2 value, verification standard, issuing authority, "
    "professional layout, signatory).\n\n"
    "red_flags: ONLY flag genuine concerns:\n"
    "- Watermark text: SAMPLE, DRAFT, TEST, VOID, SPECIMEN\n"
    "- Placeholder text: Lorem ipsum, [COMPANY NAME], [INSERT DATE], {{placeholder}}\n"
    "- Logical impossibility: expiry date before issue date\n"
    "- Future issue date (issued after today)\n"
    "- Contradictory data: negative CO2, absurd figures\n\n"
    "Do NOT flag: digital/generated PDF, no wet signature, simple layout, missing stamp, "
    "scanned appearance, future expiry date, formatting choices."
)

EXTRACTION_PROMPT = (
    "Extract structured data from this carbon compliance document.\n\n"
    "co2_value: numeric only, no units. Examples: '1,250 tonnes CO2e' -> 1250.0. null if absent.\n"
    "co2_unit: one of tonnes/kg/metric_tons. Default tonnes.\n"
    "issue_date: YYYY-MM-DD. Look for Issue Date, Date of Issue, Certified on, Report Date. null if absent.\n"
    "expiry_date: YYYY-MM-DD. Look for Valid Until, Expiry Date, Expires, Period End. "
    "Future expiry dates are correct. null if absent.\n"
    "issuing_authority: org name that issued or verified this document. Empty string if absent.\n"
    "certificate_number: any reference/cert ID. Empty string if absent.\n"
    "verification_standard: e.g. ISO 14064, GHG Protocol, Verra VCS, Gold Standard. Empty string if absent.\n\n"
    "Confidence 0-100: explicitly labelled and clearly readable=85-98, "
    "implied or non-standard label=70-85, partially obscured=50-70, inferred=30-50, absent=0.\n\n"
    "Rules: co2_value is a number or null. Dates are YYYY-MM-DD strings or null. "
    "Text fields are empty string when absent, never null."
)