import io
import base64
import logging
from decimal import Decimal

import PIL.Image

from .langchain_client import LangChainClient
from .schemas import ReadabilityOutput
from .document_cache import get_cached, set_cached
from ..models import AIAuditLog

logger = logging.getLogger(__name__)

_PROMPT = """Look at this document image and assess its readability.

Rules:
- Set is_readable to FALSE only if the document is completely blank, fully corrupted, or pure noise.
- Set is_readable to TRUE for everything else — digital PDFs, scans, photos, tilted, slightly blurry.
- quality_score: 0-100
  - Digital/computer-generated PDF: 80-95
  - Clear scan: 70-85
  - Photo of document: 60-75
  - Blurry but readable: 40-60
  - Almost unreadable: 10-30
  - Blank or corrupt: 0-10
- language: detected language or "English" if unsure
- issues: list any problems, can be empty

Digital PDFs generated by computer should score 80+ and is_readable=true."""


class ReadabilityChecker:

    def __init__(self):
        self.client = LangChainClient()

    def check(self, image_base64: str, validation, file_path: str = ""):
        
        if file_path:
            cached = get_cached(file_path, "readability")
            if cached:
                logger.info(
                    "ReadabilityChecker: cache hit | validation=%s", validation.id
                )
                return True, cached, None

        try:
            PIL.Image.open(io.BytesIO(base64.b64decode(image_base64)))
        except Exception as exc:
            logger.exception(
                "ReadabilityChecker: image decode failed | validation=%s", validation.id
            )
            result = self._default_pass(f"Image decode error: {exc}")
            return True, result, None

        success, output, error = self.client.call_structured(
            prompt=_PROMPT,
            image_base64=image_base64,
            schema=ReadabilityOutput,
        )

        AIAuditLog.objects.create(
            document_validation=validation,
            validation_step="readability",
            prompt_sent=_PROMPT,
            raw_response=str(output.model_dump()) if output else (error or ""),
            success=success,
            error_message=error or "",
            model_used="gemini-2.5-flash",
        )

        if not success or output is None:
            logger.warning(
                "ReadabilityChecker: Gemini failed | validation=%s — %s", validation.id, error
            )
            result = self._default_pass(f"API call failed: {error}")
            return True, result, None

        is_readable = output.is_readable
        if output.quality_score > 20:
            is_readable = True

        result = {
            "is_readable": is_readable,
            "quality_score": float(output.quality_score),
            "language": output.language,
            "issues": output.issues,
        }

        if file_path:
            set_cached(file_path, "readability", result)

        logger.info(
            "ReadabilityChecker: done | validation=%s readable=%s score=%.1f",
            validation.id, is_readable, output.quality_score,
        )
        return True, result, None

    def _default_pass(self, reason: str) -> dict:
        return {
            "is_readable": True,
            "quality_score": 60.0,
            "language": "Unknown",
            "issues": [reason],
        }