# Generated by Django 6.0.1 on 2026-02-19 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_organization_email_verification_token_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("vendor_created", "Vendor Created"),
                            ("vendor_updated", "Vendor Updated"),
                            ("vendor_deleted", "Vendor Deleted"),
                            ("document_uploaded", "Document Uploaded"),
                            ("document_deleted", "Document Deleted"),
                            ("validation_triggered", "Validation Triggered"),
                            ("validation_completed", "Validation Completed"),
                            ("review_resolved", "Review Resolved"),
                            ("message_sent", "Message Sent"),
                            ("user_login", "User Login"),
                            ("user_logout", "User Logout"),
                            ("report_generated", "Report Generated"),
                            ("report_approved", "Report Approved"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entity_type", models.CharField(blank=True, max_length=50)),
                ("entity_id", models.CharField(blank=True, max_length=100)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="audit_logs__organiz_adc99e_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audit_logs__action_235999_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_logs__entity__f2c7b5_idx",
                    ),
                ],
            },
        ),
    ]
