# Generated by Django 5.2.12 on 2026-04-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0002_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("vendor_created", "Vendor Created"),
                    ("vendor_updated", "Vendor Updated"),
                    ("vendor_deleted", "Vendor Deleted"),
                    ("document_uploaded", "Document Uploaded"),
                    ("document_deleted", "Document Deleted"),
                    ("document_reupload_requested", "Document Reupload Requested"),
                    ("validation_triggered", "Validation Triggered"),
                    ("validation_completed", "Validation Completed"),
                    ("review_resolved", "Review Resolved"),
                    ("message_sent", "Message Sent"),
                    ("user_created", "User Created"),
                    ("user_login", "User Login"),
                    ("user_logout", "User Logout"),
                    ("report_generated", "Report Generated"),
                    ("report_approved", "Report Approved"),
                    ("email_sent", "Email Sent"),
                    ("bulk_upload_completed", "Bulk Upload Completed"),
                    ("chat_invite_sent", "Chat Invite Sent"),
                ],
                max_length=50,
            ),
        ),
    ]
