# Generated by Django 6.0.1 on 2026-02-11 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_organization_email_verification_token_and_more"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("requires_review", "Requires Manual Review"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("readability", "Readability Check"),
                            ("relevance", "Relevance Classification"),
                            ("authenticity", "Authenticity Analysis"),
                            ("extraction", "Metadata Extraction"),
                            ("risk_analysis", "Risk Analysis"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_processing_time_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                ("readability_passed", models.BooleanField(blank=True, null=True)),
                (
                    "readability_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("readability_issues", models.JSONField(blank=True, default=list)),
                ("is_relevant", models.BooleanField(blank=True, null=True)),
                (
                    "detected_document_type",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "relevance_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "authenticity_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("authenticity_indicators", models.JSONField(blank=True, default=list)),
                ("authenticity_red_flags", models.JSONField(blank=True, default=list)),
                (
                    "overall_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("requires_manual_review", models.BooleanField(default=False)),
                ("flagged_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="vendors.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_validations",
            },
        ),
        migrations.CreateModel(
            name="AIAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "validation_step",
                    models.CharField(
                        choices=[
                            ("readability", "Readability Check"),
                            ("relevance", "Relevance Classification"),
                            ("authenticity", "Authenticity Analysis"),
                            ("extraction", "Metadata Extraction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt_sent", models.TextField()),
                ("raw_response", models.TextField()),
                ("parsed_response", models.JSONField(blank=True, default=dict)),
                (
                    "model_used",
                    models.CharField(default="gemini-1.5-flash", max_length=100),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document_validation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="ai_validation.documentvalidation",
                    ),
                ),
            ],
            options={
                "db_table": "ai_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "co2_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "co2_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tonnes", "Metric Tonnes CO2e"),
                            ("kg", "Kilograms CO2e"),
                            ("metric_tons", "Metric Tons CO2e"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "co2_extraction_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "issue_date_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "expiry_date_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("issuing_authority", models.CharField(blank=True, max_length=500)),
                (
                    "issuing_authority_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("certificate_number", models.CharField(blank=True, max_length=255)),
                ("verification_standard", models.CharField(blank=True, max_length=100)),
                ("raw_extracted_data", models.JSONField(blank=True, default=dict)),
                ("extraction_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_metadata",
                        to="vendors.document",
                    ),
                ),
                (
                    "document_validation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="ai_validation.documentvalidation",
                    ),
                ),
            ],
            options={
                "db_table": "extracted_metadata",
            },
        ),
        migrations.CreateModel(
            name="IndustryEmissionThreshold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("low_threshold", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "medium_threshold",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "high_threshold",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "critical_threshold",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "industry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_threshold",
                        to="vendors.industry",
                    ),
                ),
            ],
            options={
                "db_table": "industry_emission_thresholds",
            },
        ),
        migrations.CreateModel(
            name="ManualReviewQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("resolution_decision", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_validation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_reviews",
                        to="ai_validation.documentvalidation",
                    ),
                ),
            ],
            options={
                "db_table": "manual_review_queue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorRiskProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total_documents", models.IntegerField(default=0)),
                ("validated_documents", models.IntegerField(default=0)),
                ("flagged_documents", models.IntegerField(default=0)),
                (
                    "total_co2_emissions",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("exceeds_threshold", models.BooleanField(default=False)),
                (
                    "avg_document_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_profile",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_risk_profiles",
            },
        ),
        migrations.AddIndex(
            model_name="documentvalidation",
            index=models.Index(fields=["status"], name="document_va_status_a0c98b_idx"),
        ),
        migrations.AddIndex(
            model_name="documentvalidation",
            index=models.Index(
                fields=["-created_at"], name="document_va_created_bc2fbf_idx"
            ),
        ),
    ]
