# Generated by Django 6.0.1 on 2026-02-20 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_organization_email_verification_token_and_more"),
        ("vendors", "0002_remove_document_upload_token_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("vendor_risk", "Vendor Risk Report"),
                            ("compliance_summary", "Compliance Summary"),
                            ("emissions_overview", "Emissions Overview"),
                            ("document_audit", "Document Audit Report"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="accounts.organization",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "report_type"],
                        name="reports_rep_organiz_bdc0af_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="reports_rep_organiz_ae5072_idx",
                    ),
                ],
            },
        ),
    ]
