# Generated by Django 5.2.12 on 2026-04-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("vendor_risk", "Vendor Risk Report"),
                    ("compliance_summary", "Compliance Summary"),
                    ("emissions_overview", "Emissions Overview"),
                    ("document_audit", "Document Audit Report"),
                    ("vendor_compliance_report", "Vendor Compliance Report"),
                ],
                max_length=30,
            ),
        ),
    ]
