# Generated by Django 6.0.1 on 2026-02-19 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_organization_email_verification_token_and_more"),
        ("vendors", "0002_remove_document_upload_token_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender_display_name", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("internal_note", "Internal Note"),
                            ("vendor_facing", "Vendor Facing"),
                            ("vendor_reply", "Vendor Reply"),
                        ],
                        default="internal_note",
                        max_length=20,
                    ),
                ),
                ("email_sent", models.BooleanField(default=False)),
                ("email_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_messages",
                        to="accounts.organization",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "organization"],
                        name="communicati_vendor__31439b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="communicati_created_f78899_idx"
                    ),
                ],
            },
        ),
    ]
