# Generated by Django 5.2.12 on 2026-03-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_chattoken_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chattoken",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="chattoken",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
