# Generated by Django 6.0.1 on 2026-02-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="upload_token",
        ),
        migrations.RemoveField(
            model_name="document",
            name="upload_token_expires_at",
        ),
        migrations.AddField(
            model_name="vendor",
            name="upload_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="upload_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
