# Generated by Django 6.0.1 on 2026-03-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_remove_document_upload_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="upload_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
